spring.application.name=toeicLearning
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/toeiclearning?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXNlY3VyZS1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLXByb2plY3Q=}
jwt.expiration=${JWT_EXPIRATION:86400000}